var data1 = [{"n_code":"N1","inpatient":1,"mean":1,"year":2013,"ncode_name":"Amputation of both lower limbs","ncode_name_short":"amp both lower"},
{"n_code":"N10","inpatient":1,"mean":0.7886254,"year":2013,"ncode_name":"Lower airway burns","ncode_name_short":"airway burns"},
{"n_code":"N11","inpatient":1,"mean":0.9969938,"year":2013,"ncode_name":"Dislocation of hip","ncode_name_short":"disloc hip"},
{"n_code":"N12","inpatient":1,"mean":0.156155,"year":2013,"ncode_name":"Dislocation of knee","ncode_name_short":"disloc knee"},
{"n_code":"N13","inpatient":1,"mean":0.0486407,"year":2013,"ncode_name":"Dislocation of shoulder","ncode_name_short":"disloc shoulder"},
{"n_code":"N14","inpatient":1,"mean":0.997771,"year":2013,"ncode_name":"Other injuries of muscle & tendon and other dislocations","ncode_name_short":"other disloc"},
{"n_code":"N15","inpatient":1,"mean":0.4616309,"year":2013,"ncode_name":"Fracture of clavicle, scapula, or humerus","ncode_name_short":"fract clavicle/others"},
{"n_code":"N16","inpatient":1,"mean":0.2779582,"year":2013,"ncode_name":"Fracture of face bone","ncode_name_short":"fract face"},
{"n_code":"N17","inpatient":1,"mean":0.9994263,"year":2013,"ncode_name":"Fracture of foot bone","ncode_name_short":"fract foot"},
{"n_code":"N18","inpatient":1,"mean":0.8483185,"year":2013,"ncode_name":"Fracture of hand bone","ncode_name_short":"fract hand"},
{"n_code":"N19","inpatient":1,"mean":1,"year":2013,"ncode_name":"Fracture of neck of femur","ncode_name_short":"fract neck of femur"},
{"n_code":"N2","inpatient":1,"mean":1,"year":2013,"ncode_name":"Amputation of both upper limbs","ncode_name_short":"amp both upper"},
{"n_code":"N20","inpatient":1,"mean":1,"year":2013,"ncode_name":"Fracture of patella, tibia, fibula, or ankle","ncode_name_short":"fract patella/others"},
{"n_code":"N21","inpatient":1,"mean":0.3371986,"year":2013,"ncode_name":"Fracture of pelvis","ncode_name_short":"fract pelvis"},
{"n_code":"N22","inpatient":1,"mean":0.4797788,"year":2013,"ncode_name":"Fracture of radius or ulna","ncode_name_short":"fract radius/ulna"},
{"n_code":"N23","inpatient":1,"mean":0.689898,"year":2013,"ncode_name":"Fracture of skull","ncode_name_short":"fract skull"},
{"n_code":"N24","inpatient":1,"mean":0.1665469,"year":2013,"ncode_name":"Fracture of sternum or rib(s)","ncode_name_short":"fract sternum/ribs"},
{"n_code":"N25","inpatient":1,"mean":0.4860595,"year":2013,"ncode_name":"Fracture of vertebral column","ncode_name_short":"fract vertebral c"},
{"n_code":"N26","inpatient":1,"mean":1,"year":2013,"ncode_name":"Fracture of femur, other than femoral neck","ncode_name_short":"fract femur"},
{"n_code":"N27","inpatient":1,"mean":0.5519395,"year":2013,"ncode_name":"Minor traumatic brain injury","ncode_name_short":"minor TBI"},
{"n_code":"N28","inpatient":1,"mean":0.56186,"year":2013,"ncode_name":"Moderate to severe traumatic brain injury","ncode_name_short":"mod/severe TBI"},
{"n_code":"N3","inpatient":1,"mean":1,"year":2013,"ncode_name":"Amputation of finger (excluding thumb)","ncode_name_short":"amp finger"},
{"n_code":"N33","inpatient":1,"mean":0.2532412,"year":2013,"ncode_name":"Spinal cord lesion at neck level","ncode_name_short":"spinal les at neck"},
{"n_code":"N34","inpatient":1,"mean":0.7252885,"year":2013,"ncode_name":"Spinal cord lesion below neck level","ncode_name_short":"spinal les below neck"},
{"n_code":"N35","inpatient":1,"mean":0.024244,"year":2013,"ncode_name":"Non-fatal submersion","ncode_name_short":"submersion"},
{"n_code":"N36","inpatient":1,"mean":0.024244,"year":2013,"ncode_name":"Asphyxiation","ncode_name_short":"asphyxiation"},
{"n_code":"N37","inpatient":1,"mean":0.5030606,"year":2013,"ncode_name":"Crush injury","ncode_name_short":"crush inj"},
{"n_code":"N38","inpatient":1,"mean":0.986097,"year":2013,"ncode_name":"Injured nerves","ncode_name_short":"injured nerves"},
{"n_code":"N39","inpatient":1,"mean":0.535474,"year":2013,"ncode_name":"Injury to eyes (including foreign body eye)","ncode_name_short":"eye inj"},
{"n_code":"N4","inpatient":1,"mean":1,"year":2013,"ncode_name":"Amputation of one lower limb","ncode_name_short":"amp 1 lower"},
{"n_code":"N40","inpatient":1,"mean":0.9974149,"year":2013,"ncode_name":"Open wound","ncode_name_short":"open wound"},
{"n_code":"N41","inpatient":1,"mean":0.0704518,"year":2013,"ncode_name":"Poisoning","ncode_name_short":"poisin"},
{"n_code":"N42","inpatient":1,"mean":0.6212282,"year":2013,"ncode_name":"Severe chest Injury","ncode_name_short":"sev chest inj"},
{"n_code":"N43","inpatient":1,"mean":0.6657317,"year":2013,"ncode_name":"Internal hemorrhage in abdomen or pelvis","ncode_name_short":"hemorr abdomen"},
{"n_code":"N44","inpatient":1,"mean":0.9976745,"year":2013,"ncode_name":"Contusion","ncode_name_short":"contusion"},
{"n_code":"N45","inpatient":1,"mean":0.9008635,"year":2013,"ncode_name":"Environmental factors (e.g. temperature, pressure, electricity)","ncode_name_short":"environ factors"},
{"n_code":"N46","inpatient":1,"mean":0.975513,"year":2013,"ncode_name":"Complications of medical treatment","ncode_name_short":"medical complic"},
{"n_code":"N48","inpatient":1,"mean":0.9988433,"year":2013,"ncode_name":"Multiple significant injuries","ncode_name_short":"multiple sig injs"},
{"n_code":"N5","inpatient":1,"mean":1,"year":2013,"ncode_name":"Amputation of one upper limb","ncode_name_short":"amp 1 upper"},
{"n_code":"N6","inpatient":1,"mean":1,"year":2013,"ncode_name":"Amputation of thumb","ncode_name_short":"amp thumb"},
{"n_code":"N7","inpatient":1,"mean":1,"year":2013,"ncode_name":"Amputation of toe","ncode_name_short":"amp toe"},
{"n_code":"N8","inpatient":1,"mean":0.5215389,"year":2013,"ncode_name":"Burns with <20% total burned surface area","ncode_name_short":"burns <20%"},
{"n_code":"N9","inpatient":1,"mean":0.5215389,"year":2013,"ncode_name":"Burns with >=20% total burned surface area or >=10% if burns include face and/or hands","ncode_name_short":"burns >=20%"}]